title: Arcana _by HTML5 UP_
author:
  name: Untitled
  # email: 'joe@example.com'
metadata:
  description: 'Port of HTML5UP Arcana theme to Grav content management system.'
  # rights: Everything is awesome.